//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCompositionAgencia.ServiceComponentTerrestre {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacaoOnibusVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoTerrestre")]
    [System.SerializableAttribute()]
    public partial class InformacaoOnibusVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceCompositionAgencia.ServiceComponentTerrestre.AssentoOnibusVO[] AssentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceCompositionAgencia.ServiceComponentTerrestre.AssentoOnibusVO[] Assentos {
            get {
                return this.AssentosField;
            }
            set {
                if ((object.ReferenceEquals(this.AssentosField, value) != true)) {
                    this.AssentosField = value;
                    this.RaisePropertyChanged("Assentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeDestino {
            get {
                return this.CodigoCidadeDestinoField;
            }
            set {
                if ((this.CodigoCidadeDestinoField.Equals(value) != true)) {
                    this.CodigoCidadeDestinoField = value;
                    this.RaisePropertyChanged("CodigoCidadeDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeOrigem {
            get {
                return this.CodigoCidadeOrigemField;
            }
            set {
                if ((this.CodigoCidadeOrigemField.Equals(value) != true)) {
                    this.CodigoCidadeOrigemField = value;
                    this.RaisePropertyChanged("CodigoCidadeOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssentoOnibusVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoTerrestre")]
    [System.SerializableAttribute()]
    public partial class AssentoOnibusVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LivreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Livre {
            get {
                return this.LivreField;
            }
            set {
                if ((this.LivreField.Equals(value) != true)) {
                    this.LivreField = value;
                    this.RaisePropertyChanged("Livre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaOnibusVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoTerrestre")]
    [System.SerializableAttribute()]
    public partial class ReservaOnibusVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Assento {
            get {
                return this.AssentoField;
            }
            set {
                if ((this.AssentoField.Equals(value) != true)) {
                    this.AssentoField = value;
                    this.RaisePropertyChanged("Assento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeDestino {
            get {
                return this.CodigoCidadeDestinoField;
            }
            set {
                if ((this.CodigoCidadeDestinoField.Equals(value) != true)) {
                    this.CodigoCidadeDestinoField = value;
                    this.RaisePropertyChanged("CodigoCidadeDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeOrigem {
            get {
                return this.CodigoCidadeOrigemField;
            }
            set {
                if ((this.CodigoCidadeOrigemField.Equals(value) != true)) {
                    this.CodigoCidadeOrigemField = value;
                    this.RaisePropertyChanged("CodigoCidadeOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceComponentTerrestre.IServiceTerrestre")]
    public interface IServiceTerrestre {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTerrestre/VerificarPrecos", ReplyAction="http://tempuri.org/IServiceTerrestre/VerificarPrecosResponse")]
        ServiceCompositionAgencia.ServiceComponentTerrestre.InformacaoOnibusVO VerificarPrecos(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTerrestre/VerificarPrecos", ReplyAction="http://tempuri.org/IServiceTerrestre/VerificarPrecosResponse")]
        System.Threading.Tasks.Task<ServiceCompositionAgencia.ServiceComponentTerrestre.InformacaoOnibusVO> VerificarPrecosAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTerrestre/ComprarPassagem", ReplyAction="http://tempuri.org/IServiceTerrestre/ComprarPassagemResponse")]
        ServiceCompositionAgencia.ServiceComponentTerrestre.ReservaOnibusVO ComprarPassagem(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTerrestre/ComprarPassagem", ReplyAction="http://tempuri.org/IServiceTerrestre/ComprarPassagemResponse")]
        System.Threading.Tasks.Task<ServiceCompositionAgencia.ServiceComponentTerrestre.ReservaOnibusVO> ComprarPassagemAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTerrestreChannel : global::ServiceCompositionAgencia.ServiceComponentTerrestre.IServiceTerrestre, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTerrestreClient : System.ServiceModel.ClientBase<global::ServiceCompositionAgencia.ServiceComponentTerrestre.IServiceTerrestre>, global::ServiceCompositionAgencia.ServiceComponentTerrestre.IServiceTerrestre {
        
        public ServiceTerrestreClient() {
        }
        
        public ServiceTerrestreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTerrestreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTerrestreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTerrestreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceCompositionAgencia.ServiceComponentTerrestre.InformacaoOnibusVO VerificarPrecos(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data) {
            return base.Channel.VerificarPrecos(codigoCidadeOrigem, codigoCidadeDestino, data);
        }
        
        public System.Threading.Tasks.Task<ServiceCompositionAgencia.ServiceComponentTerrestre.InformacaoOnibusVO> VerificarPrecosAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data) {
            return base.Channel.VerificarPrecosAsync(codigoCidadeOrigem, codigoCidadeDestino, data);
        }
        
        public ServiceCompositionAgencia.ServiceComponentTerrestre.ReservaOnibusVO ComprarPassagem(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento) {
            return base.Channel.ComprarPassagem(codigoCidadeOrigem, codigoCidadeDestino, data, numeroAssento);
        }
        
        public System.Threading.Tasks.Task<ServiceCompositionAgencia.ServiceComponentTerrestre.ReservaOnibusVO> ComprarPassagemAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento) {
            return base.Channel.ComprarPassagemAsync(codigoCidadeOrigem, codigoCidadeDestino, data, numeroAssento);
        }
    }
}
