//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCompositionAgencia.ServiceComponentCorreio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoVO", Namespace="http://schemas.datacontract.org/2004/07/ServiceCorreio")]
    [System.SerializableAttribute()]
    public partial class EnderecoVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCidade {
            get {
                return this.NomeCidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCidadeField, value) != true)) {
                    this.NomeCidadeField = value;
                    this.RaisePropertyChanged("NomeCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiglaEstado {
            get {
                return this.SiglaEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaEstadoField, value) != true)) {
                    this.SiglaEstadoField = value;
                    this.RaisePropertyChanged("SiglaEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceComponentCorreio.IServiceCorreio")]
    public interface IServiceCorreio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCorreio/ObterEndereco", ReplyAction="http://tempuri.org/IServiceCorreio/ObterEnderecoResponse")]
        ServiceCompositionAgencia.ServiceComponentCorreio.EnderecoVO ObterEndereco(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCorreio/ObterEndereco", ReplyAction="http://tempuri.org/IServiceCorreio/ObterEnderecoResponse")]
        System.Threading.Tasks.Task<ServiceCompositionAgencia.ServiceComponentCorreio.EnderecoVO> ObterEnderecoAsync(string cep);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCorreioChannel : global::ServiceCompositionAgencia.ServiceComponentCorreio.IServiceCorreio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCorreioClient : System.ServiceModel.ClientBase<global::ServiceCompositionAgencia.ServiceComponentCorreio.IServiceCorreio>, global::ServiceCompositionAgencia.ServiceComponentCorreio.IServiceCorreio {
        
        public ServiceCorreioClient() {
        }
        
        public ServiceCorreioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCorreioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCorreioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCorreioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceCompositionAgencia.ServiceComponentCorreio.EnderecoVO ObterEndereco(string cep) {
            return base.Channel.ObterEndereco(cep);
        }
        
        public System.Threading.Tasks.Task<ServiceCompositionAgencia.ServiceComponentCorreio.EnderecoVO> ObterEnderecoAsync(string cep) {
            return base.Channel.ObterEnderecoAsync(cep);
        }
    }
}
