//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAgencia.ServiceCompositionAgencia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacaoQuartosVO", Namespace="http://schemas.datacontract.org/2004/07/ServiceHotel")]
    [System.SerializableAttribute()]
    public partial class InformacaoQuartosVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationAgencia.ServiceCompositionAgencia.QuartoVO[] QuartosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoHotel {
            get {
                return this.CodigoHotelField;
            }
            set {
                if ((this.CodigoHotelField.Equals(value) != true)) {
                    this.CodigoHotelField = value;
                    this.RaisePropertyChanged("CodigoHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationAgencia.ServiceCompositionAgencia.QuartoVO[] Quartos {
            get {
                return this.QuartosField;
            }
            set {
                if ((object.ReferenceEquals(this.QuartosField, value) != true)) {
                    this.QuartosField = value;
                    this.RaisePropertyChanged("Quartos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuartoVO", Namespace="http://schemas.datacontract.org/2004/07/ServiceHotel")]
    [System.SerializableAttribute()]
    public partial class QuartoVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HidromassagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TelevisaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VistaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hidromassagem {
            get {
                return this.HidromassagemField;
            }
            set {
                if ((this.HidromassagemField.Equals(value) != true)) {
                    this.HidromassagemField = value;
                    this.RaisePropertyChanged("Hidromassagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Televisao {
            get {
                return this.TelevisaoField;
            }
            set {
                if ((this.TelevisaoField.Equals(value) != true)) {
                    this.TelevisaoField = value;
                    this.RaisePropertyChanged("Televisao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vista {
            get {
                return this.VistaField;
            }
            set {
                if ((this.VistaField.Equals(value) != true)) {
                    this.VistaField = value;
                    this.RaisePropertyChanged("Vista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaVO", Namespace="http://schemas.datacontract.org/2004/07/ServiceHotel")]
    [System.SerializableAttribute()]
    public partial class ReservaVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationAgencia.ServiceCompositionAgencia.QuartoVO QuartoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RealizadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationAgencia.ServiceCompositionAgencia.QuartoVO Quarto {
            get {
                return this.QuartoField;
            }
            set {
                if ((object.ReferenceEquals(this.QuartoField, value) != true)) {
                    this.QuartoField = value;
                    this.RaisePropertyChanged("Quarto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Realizado {
            get {
                return this.RealizadoField;
            }
            set {
                if ((this.RealizadoField.Equals(value) != true)) {
                    this.RealizadoField = value;
                    this.RaisePropertyChanged("Realizado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoVO", Namespace="http://schemas.datacontract.org/2004/07/ServiceCorreio")]
    [System.SerializableAttribute()]
    public partial class EnderecoVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCidade {
            get {
                return this.NomeCidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCidadeField, value) != true)) {
                    this.NomeCidadeField = value;
                    this.RaisePropertyChanged("NomeCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiglaEstado {
            get {
                return this.SiglaEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaEstadoField, value) != true)) {
                    this.SiglaEstadoField = value;
                    this.RaisePropertyChanged("SiglaEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacaoAviaoVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoAereo")]
    [System.SerializableAttribute()]
    public partial class InformacaoAviaoVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationAgencia.ServiceCompositionAgencia.AssentoAviaoVO[] AssentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationAgencia.ServiceCompositionAgencia.AssentoAviaoVO[] Assentos {
            get {
                return this.AssentosField;
            }
            set {
                if ((object.ReferenceEquals(this.AssentosField, value) != true)) {
                    this.AssentosField = value;
                    this.RaisePropertyChanged("Assentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeDestino {
            get {
                return this.CodigoCidadeDestinoField;
            }
            set {
                if ((this.CodigoCidadeDestinoField.Equals(value) != true)) {
                    this.CodigoCidadeDestinoField = value;
                    this.RaisePropertyChanged("CodigoCidadeDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeOrigem {
            get {
                return this.CodigoCidadeOrigemField;
            }
            set {
                if ((this.CodigoCidadeOrigemField.Equals(value) != true)) {
                    this.CodigoCidadeOrigemField = value;
                    this.RaisePropertyChanged("CodigoCidadeOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssentoAviaoVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoAereo")]
    [System.SerializableAttribute()]
    public partial class AssentoAviaoVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileiraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LivreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fileira {
            get {
                return this.FileiraField;
            }
            set {
                if ((object.ReferenceEquals(this.FileiraField, value) != true)) {
                    this.FileiraField = value;
                    this.RaisePropertyChanged("Fileira");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Livre {
            get {
                return this.LivreField;
            }
            set {
                if ((this.LivreField.Equals(value) != true)) {
                    this.LivreField = value;
                    this.RaisePropertyChanged("Livre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaAviaoVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoAereo")]
    [System.SerializableAttribute()]
    public partial class ReservaAviaoVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileiraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Assento {
            get {
                return this.AssentoField;
            }
            set {
                if ((this.AssentoField.Equals(value) != true)) {
                    this.AssentoField = value;
                    this.RaisePropertyChanged("Assento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeDestino {
            get {
                return this.CodigoCidadeDestinoField;
            }
            set {
                if ((this.CodigoCidadeDestinoField.Equals(value) != true)) {
                    this.CodigoCidadeDestinoField = value;
                    this.RaisePropertyChanged("CodigoCidadeDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeOrigem {
            get {
                return this.CodigoCidadeOrigemField;
            }
            set {
                if ((this.CodigoCidadeOrigemField.Equals(value) != true)) {
                    this.CodigoCidadeOrigemField = value;
                    this.RaisePropertyChanged("CodigoCidadeOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fileira {
            get {
                return this.FileiraField;
            }
            set {
                if ((object.ReferenceEquals(this.FileiraField, value) != true)) {
                    this.FileiraField = value;
                    this.RaisePropertyChanged("Fileira");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacaoOnibusVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoTerrestre")]
    [System.SerializableAttribute()]
    public partial class InformacaoOnibusVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationAgencia.ServiceCompositionAgencia.AssentoOnibusVO[] AssentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationAgencia.ServiceCompositionAgencia.AssentoOnibusVO[] Assentos {
            get {
                return this.AssentosField;
            }
            set {
                if ((object.ReferenceEquals(this.AssentosField, value) != true)) {
                    this.AssentosField = value;
                    this.RaisePropertyChanged("Assentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeDestino {
            get {
                return this.CodigoCidadeDestinoField;
            }
            set {
                if ((this.CodigoCidadeDestinoField.Equals(value) != true)) {
                    this.CodigoCidadeDestinoField = value;
                    this.RaisePropertyChanged("CodigoCidadeDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeOrigem {
            get {
                return this.CodigoCidadeOrigemField;
            }
            set {
                if ((this.CodigoCidadeOrigemField.Equals(value) != true)) {
                    this.CodigoCidadeOrigemField = value;
                    this.RaisePropertyChanged("CodigoCidadeOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssentoOnibusVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoTerrestre")]
    [System.SerializableAttribute()]
    public partial class AssentoOnibusVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LivreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Livre {
            get {
                return this.LivreField;
            }
            set {
                if ((this.LivreField.Equals(value) != true)) {
                    this.LivreField = value;
                    this.RaisePropertyChanged("Livre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaOnibusVO", Namespace="http://schemas.datacontract.org/2004/07/ServicoTerrestre")]
    [System.SerializableAttribute()]
    public partial class ReservaOnibusVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoCidadeOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Assento {
            get {
                return this.AssentoField;
            }
            set {
                if ((this.AssentoField.Equals(value) != true)) {
                    this.AssentoField = value;
                    this.RaisePropertyChanged("Assento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeDestino {
            get {
                return this.CodigoCidadeDestinoField;
            }
            set {
                if ((this.CodigoCidadeDestinoField.Equals(value) != true)) {
                    this.CodigoCidadeDestinoField = value;
                    this.RaisePropertyChanged("CodigoCidadeDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCidadeOrigem {
            get {
                return this.CodigoCidadeOrigemField;
            }
            set {
                if ((this.CodigoCidadeOrigemField.Equals(value) != true)) {
                    this.CodigoCidadeOrigemField = value;
                    this.RaisePropertyChanged("CodigoCidadeOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCompositionAgencia.IServiceAgencia")]
    public interface IServiceAgencia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/VerificarQuartos", ReplyAction="http://tempuri.org/IServiceAgencia/VerificarQuartosResponse")]
        WebApplicationAgencia.ServiceCompositionAgencia.InformacaoQuartosVO VerificarQuartos(int codigoHotel, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/VerificarQuartos", ReplyAction="http://tempuri.org/IServiceAgencia/VerificarQuartosResponse")]
        System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.InformacaoQuartosVO> VerificarQuartosAsync(int codigoHotel, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ReservarQuarto", ReplyAction="http://tempuri.org/IServiceAgencia/ReservarQuartoResponse")]
        WebApplicationAgencia.ServiceCompositionAgencia.ReservaVO ReservarQuarto(int codigoHotel, string nome, System.DateTime data, int codigoTipoQuarto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ReservarQuarto", ReplyAction="http://tempuri.org/IServiceAgencia/ReservarQuartoResponse")]
        System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.ReservaVO> ReservarQuartoAsync(int codigoHotel, string nome, System.DateTime data, int codigoTipoQuarto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ObterEndereco", ReplyAction="http://tempuri.org/IServiceAgencia/ObterEnderecoResponse")]
        WebApplicationAgencia.ServiceCompositionAgencia.EnderecoVO ObterEndereco(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ObterEndereco", ReplyAction="http://tempuri.org/IServiceAgencia/ObterEnderecoResponse")]
        System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.EnderecoVO> ObterEnderecoAsync(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/VerificarPrecosAviao", ReplyAction="http://tempuri.org/IServiceAgencia/VerificarPrecosAviaoResponse")]
        WebApplicationAgencia.ServiceCompositionAgencia.InformacaoAviaoVO VerificarPrecosAviao(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/VerificarPrecosAviao", ReplyAction="http://tempuri.org/IServiceAgencia/VerificarPrecosAviaoResponse")]
        System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.InformacaoAviaoVO> VerificarPrecosAviaoAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ComprarPassagemAviao", ReplyAction="http://tempuri.org/IServiceAgencia/ComprarPassagemAviaoResponse")]
        WebApplicationAgencia.ServiceCompositionAgencia.ReservaAviaoVO ComprarPassagemAviao(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento, string fileira);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ComprarPassagemAviao", ReplyAction="http://tempuri.org/IServiceAgencia/ComprarPassagemAviaoResponse")]
        System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.ReservaAviaoVO> ComprarPassagemAviaoAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento, string fileira);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/VerificarPrecosOnibus", ReplyAction="http://tempuri.org/IServiceAgencia/VerificarPrecosOnibusResponse")]
        WebApplicationAgencia.ServiceCompositionAgencia.InformacaoOnibusVO VerificarPrecosOnibus(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/VerificarPrecosOnibus", ReplyAction="http://tempuri.org/IServiceAgencia/VerificarPrecosOnibusResponse")]
        System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.InformacaoOnibusVO> VerificarPrecosOnibusAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ComprarPassagemOnibus", ReplyAction="http://tempuri.org/IServiceAgencia/ComprarPassagemOnibusResponse")]
        WebApplicationAgencia.ServiceCompositionAgencia.ReservaOnibusVO ComprarPassagemOnibus(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgencia/ComprarPassagemOnibus", ReplyAction="http://tempuri.org/IServiceAgencia/ComprarPassagemOnibusResponse")]
        System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.ReservaOnibusVO> ComprarPassagemOnibusAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAgenciaChannel : global::WebApplicationAgencia.ServiceCompositionAgencia.IServiceAgencia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAgenciaClient : System.ServiceModel.ClientBase<global::WebApplicationAgencia.ServiceCompositionAgencia.IServiceAgencia>, global::WebApplicationAgencia.ServiceCompositionAgencia.IServiceAgencia {
        
        public ServiceAgenciaClient() {
        }
        
        public ServiceAgenciaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAgenciaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplicationAgencia.ServiceCompositionAgencia.InformacaoQuartosVO VerificarQuartos(int codigoHotel, System.DateTime data) {
            return base.Channel.VerificarQuartos(codigoHotel, data);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.InformacaoQuartosVO> VerificarQuartosAsync(int codigoHotel, System.DateTime data) {
            return base.Channel.VerificarQuartosAsync(codigoHotel, data);
        }
        
        public WebApplicationAgencia.ServiceCompositionAgencia.ReservaVO ReservarQuarto(int codigoHotel, string nome, System.DateTime data, int codigoTipoQuarto) {
            return base.Channel.ReservarQuarto(codigoHotel, nome, data, codigoTipoQuarto);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.ReservaVO> ReservarQuartoAsync(int codigoHotel, string nome, System.DateTime data, int codigoTipoQuarto) {
            return base.Channel.ReservarQuartoAsync(codigoHotel, nome, data, codigoTipoQuarto);
        }
        
        public WebApplicationAgencia.ServiceCompositionAgencia.EnderecoVO ObterEndereco(string cep) {
            return base.Channel.ObterEndereco(cep);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.EnderecoVO> ObterEnderecoAsync(string cep) {
            return base.Channel.ObterEnderecoAsync(cep);
        }
        
        public WebApplicationAgencia.ServiceCompositionAgencia.InformacaoAviaoVO VerificarPrecosAviao(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data) {
            return base.Channel.VerificarPrecosAviao(codigoCidadeOrigem, codigoCidadeDestino, data);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.InformacaoAviaoVO> VerificarPrecosAviaoAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data) {
            return base.Channel.VerificarPrecosAviaoAsync(codigoCidadeOrigem, codigoCidadeDestino, data);
        }
        
        public WebApplicationAgencia.ServiceCompositionAgencia.ReservaAviaoVO ComprarPassagemAviao(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento, string fileira) {
            return base.Channel.ComprarPassagemAviao(codigoCidadeOrigem, codigoCidadeDestino, data, numeroAssento, fileira);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.ReservaAviaoVO> ComprarPassagemAviaoAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento, string fileira) {
            return base.Channel.ComprarPassagemAviaoAsync(codigoCidadeOrigem, codigoCidadeDestino, data, numeroAssento, fileira);
        }
        
        public WebApplicationAgencia.ServiceCompositionAgencia.InformacaoOnibusVO VerificarPrecosOnibus(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data) {
            return base.Channel.VerificarPrecosOnibus(codigoCidadeOrigem, codigoCidadeDestino, data);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.InformacaoOnibusVO> VerificarPrecosOnibusAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data) {
            return base.Channel.VerificarPrecosOnibusAsync(codigoCidadeOrigem, codigoCidadeDestino, data);
        }
        
        public WebApplicationAgencia.ServiceCompositionAgencia.ReservaOnibusVO ComprarPassagemOnibus(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento) {
            return base.Channel.ComprarPassagemOnibus(codigoCidadeOrigem, codigoCidadeDestino, data, numeroAssento);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAgencia.ServiceCompositionAgencia.ReservaOnibusVO> ComprarPassagemOnibusAsync(int codigoCidadeOrigem, int codigoCidadeDestino, System.DateTime data, int numeroAssento) {
            return base.Channel.ComprarPassagemOnibusAsync(codigoCidadeOrigem, codigoCidadeDestino, data, numeroAssento);
        }
    }
}
